### ISSUE TITLE
Strange Blue Dot

### ISSUE THREAD

**Issue by FractalCyclone** [MOARdV/DistantObject#45]
Blue Dot from Sigma Binary / Distant Object Enhancement conflict.

Spawns from craft, single-sided texture invisible when viewed from any other direction. Not collidable, static once spawned.

The issue only presents itself when there is a binary system loaded and Distant Object Enhancement is installed.

**Already posted this to the Sigma Binary Github issue tracker as well**

![screenshot2](https://user-images.githubusercontent.com/56998435/67609282-8b1f3280-f751-11e9-9c11-156f67603bc5.png)
![screenshot0](https://user-images.githubusercontent.com/56998435/67609283-8b1f3280-f751-11e9-89c7-3332cdb08aa9.png)

> KSP 1.7.3
Kopernicus - 1.7.3.2
ModularFlightIntegrator - 1.2.6.0
Sigma Binary - 1.7.2
Distant Object Enhancement - 1.9.1.1
SigmaDunaIke

[KSP.log](https://github.com/Sigma88/Sigma-Binary/files/3774110/KSP.log)

**Comment by MOARdV** [comment]
Sigma88 contacted me about this.  As I noted with him (although more succinctly), the dot is an impostor used to represent a planetary body.  Bodies are *supposed* to be draw about 740km to 750km from the camera, so I really don't understand how that one is forming in front of the runway.

Although, in the log, there's an NRE when the body flare generator is starting up.  I am guessing Sigma Binary rearranges something in FlightGlobals in a way that DOE doesn't expect, so the NRE interrupts the flare generation code, leaving debris.

Note that I'm no longer supporting this mod, since I don't have time for KSP modding, so I don't know when or if I'll be in a position to fix this bug.

**Comment by MOARdV** [comment]
For anyone who stops by this repo looking for this bug's solution, there is a fix here: https://github.com/Sigma88/DistantObject/releases

Note that Sigma88 did not take over the mod - this was a fix to address a bug in DOE that affects Sigma Binary players (and, possibly, other mods that create barycenters).
